# Generated by Django 4.2.27 on 2025-12-22 03:20

# Django
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corptools", "0127_alter_corporationaudit_options"),
        ("authentication", "0025_userprofile_minimize_sidebar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("basic_access", "Can access the Accounting app"),
                    ("view_own_corp", "Can view own corp"),
                    ("view_all", "Can view all characters and corps"),
                    (
                        "finance_manager",
                        "Can view everything, plus submit bills/invoices",
                    ),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CharacterPayoutTaxConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "wallet_transaction_type",
                    models.CharField(
                        help_text="Transaction types to tax. eg bounty_prizes,corporate_reward_payout",
                        max_length=150,
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Corporation that sent isk to character, Blank for Any Corporation",
                        limit_choices_to={"category": "corporation"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corptools.evename",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax: Character Wallet",
                "verbose_name_plural": "Tax: Character Wallet",
            },
        ),
        migrations.CreateModel(
            name="CharacterRattingTaxConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                ("include_ess_section", models.BooleanField(default=True)),
                (
                    "region_filter",
                    models.ManyToManyField(blank=True, to="corptools.mapregion"),
                ),
            ],
            options={
                "verbose_name": "Tax: Character Ratting",
                "verbose_name_plural": "Tax: Character Ratting",
            },
        ),
        migrations.CreateModel(
            name="CorpAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=20
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "corporation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorpTaxRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("json_dump", models.TextField()),
                (
                    "total_tax",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=20, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Records: Corporate",
                "verbose_name_plural": "Records: Corporate",
            },
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=20
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLedgerEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=20
                    ),
                ),
                ("description", models.TextField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("tax", "Tax"),
                            ("fine", "Fine"),
                            ("adjustment", "Adjustment"),
                            ("charge", "Charge"),
                        ],
                        default="deposit",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="accounting.useraccount",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnclaimedTax",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("tax", "Tax"),
                            ("fine", "Fine"),
                            ("adjustment", "Adjustment"),
                            ("charge", "Charge"),
                        ],
                        default="charge",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unclaimed_taxes",
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="CorpTaxPerServiceModuleConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isk_per_service", models.IntegerField(default=20000000)),
                (
                    "module_filters",
                    models.TextField(
                        help_text="Comma Delimited list of service module types to Tax eg, Manufacturing (Standard),Manufacturing (Capitals),Manufacturing (Super Capitals)"
                    ),
                ),
                (
                    "region_filter",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Regions to limit this tax to.",
                        to="corptools.mapregion",
                    ),
                ),
                (
                    "structure_type_filter",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"group__category_id": 65},
                        to="corptools.eveitemtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax: Structure Service",
                "verbose_name_plural": "Tax: Structure Service",
            },
        ),
        migrations.CreateModel(
            name="CorpTaxPerMemberTaxConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isk_per_main", models.IntegerField(default=20000000)),
                (
                    "state",
                    models.ForeignKey(
                        help_text="State to assign this member tax rate to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.state",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax: Corp Member Main",
                "verbose_name_plural": "Tax: Corp Member Main",
            },
        ),
        migrations.CreateModel(
            name="CorpTaxPayoutTaxConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "wallet_transaction_type",
                    models.CharField(
                        help_text="Transaction types to tax. eg bounty_prizes,corporate_reward_payout",
                        max_length=150,
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Corporation that sent isk to character, Blank for Any Corporation",
                        limit_choices_to={"category": "corporation"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corptools.evename",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax: Corporate Wallet",
                "verbose_name_plural": "Tax: Corporate Wallet",
            },
        ),
        migrations.CreateModel(
            name="CorpTaxConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                (
                    "character_ratting_included",
                    models.ManyToManyField(
                        blank=True, to="accounting.characterrattingtaxconfiguration"
                    ),
                ),
                (
                    "character_taxes_included",
                    models.ManyToManyField(
                        blank=True, to="accounting.characterpayouttaxconfiguration"
                    ),
                ),
                (
                    "corporate_member_tax_included",
                    models.ManyToManyField(
                        blank=True, to="accounting.corptaxpermembertaxconfiguration"
                    ),
                ),
                (
                    "corporate_structure_tax_included",
                    models.ManyToManyField(
                        blank=True, to="accounting.corptaxperservicemoduleconfiguration"
                    ),
                ),
                (
                    "corporate_taxes_included",
                    models.ManyToManyField(
                        blank=True, to="accounting.corptaxpayouttaxconfiguration"
                    ),
                ),
                (
                    "exempted_corps",
                    models.ManyToManyField(
                        blank=True, to="eveonline.evecorporationinfo"
                    ),
                ),
                (
                    "included_alliances",
                    models.ManyToManyField(blank=True, to="eveonline.eveallianceinfo"),
                ),
            ],
            options={
                "verbose_name": "Config: Corporate",
                "verbose_name_plural": "Config: Corporate",
            },
        ),
        migrations.CreateModel(
            name="CorporatePayoutTaxRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed", models.BooleanField(default=True)),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxed",
                        to="corptools.corporationwalletjournalentry",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.corptaxrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorpLedgerEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=20
                    ),
                ),
                ("description", models.TextField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("tax", "Tax"),
                            ("fine", "Fine"),
                            ("adjustment", "Adjustment"),
                            ("charge", "Charge"),
                        ],
                        default="deposit",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="accounting.corpaccount",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterPayoutTaxRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed", models.BooleanField(default=True)),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxed",
                        to="corptools.characterwalletjournalentry",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.corptaxrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountingConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_payment_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp of the last processed payment.",
                    ),
                ),
                (
                    "bank_corp",
                    models.OneToOneField(
                        help_text="The Corporation that ISK gets sent to.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_corp",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
                (
                    "ignored_corp",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Corps to ignore deposits from",
                        related_name="ignored_corps",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CorpTaxHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "corp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecorporationinfo",
                    ),
                ),
            ],
            options={
                "unique_together": {("corp", "start_date")},
            },
        ),
    ]
