# Generated by Django 4.2.27 on 2025-12-23 22:19

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        ("corptools", "0127_alter_corporationaudit_options"),
        ("authentication", "0025_userprofile_minimize_sidebar"),
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterpayouttaxconfiguration",
            name="corporation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Corporation that sent isk to character, Blank for Any Corporation",
                limit_choices_to={"category": "corporation"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_tax_corp",
                to="corptools.evename",
            ),
        ),
        migrations.AlterField(
            model_name="characterrattingtaxconfiguration",
            name="region_filter",
            field=models.ManyToManyField(
                blank=True,
                help_text="Regions to limit this tax to.",
                related_name="character_ratting_tax_regions",
                to="corptools.mapregion",
            ),
        ),
        migrations.AlterField(
            model_name="corporatepayouttaxrecord",
            name="entry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taxed",
                related_query_name="corp_taxed",
                to="corptools.corporationwalletjournalentry",
            ),
        ),
        migrations.AlterField(
            model_name="corptaxconfiguration",
            name="exempted_corps",
            field=models.ManyToManyField(
                blank=True,
                related_name="corp_tax_exempted_corps",
                to="eveonline.evecorporationinfo",
            ),
        ),
        migrations.AlterField(
            model_name="corptaxconfiguration",
            name="included_alliances",
            field=models.ManyToManyField(
                blank=True,
                help_text="Only include corporations in these alliances. Leave blank to include all.",
                related_name="corp_tax_included_alliances",
                to="eveonline.eveallianceinfo",
            ),
        ),
        migrations.AlterField(
            model_name="corptaxhistory",
            name="corp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_history",
                to="eveonline.evecorporationinfo",
            ),
        ),
        migrations.AlterField(
            model_name="corptaxpayouttaxconfiguration",
            name="corporation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Corporation that sent isk to character, Blank for Any Corporation",
                limit_choices_to={"category": "corporation"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_corp_payout",
                to="corptools.evename",
            ),
        ),
        migrations.AlterField(
            model_name="corptaxpermembertaxconfiguration",
            name="state",
            field=models.ForeignKey(
                help_text="State to assign this member tax rate to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corp_member_tax_state",
                to="authentication.state",
            ),
        ),
        migrations.AlterField(
            model_name="corptaxperservicemoduleconfiguration",
            name="region_filter",
            field=models.ManyToManyField(
                blank=True,
                help_text="Regions to limit this tax to.",
                related_name="corp_structure_service_tax_regions",
                to="corptools.mapregion",
            ),
        ),
        migrations.AlterField(
            model_name="corptaxperservicemoduleconfiguration",
            name="structure_type_filter",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"group__category_id": 65},
                related_name="corp_structure_type_tax_structures",
                to="corptools.eveitemtype",
            ),
        ),
    ]
